### ISSUE TITLE
Develop logic to handle import data hierarchy for duplicate records found during import

### ISSUE THREAD

**Issue by arlissc** [mozilla/network-crm#6]
For the fields in the import; we need to define which system (import file or Salesforce) should win if there is data already populated in Salesforce, then which fields should be overwritten from the import and fields should be left alone if they are already populated?

**Comment by desiree-mofo** [comment]
Steph may be able to export the matches from SFMC and provide a list to me and I can export the full contact details for those individuals, send the spreadsheet to Arliss and let her determine which data values to keep/toss.
